# Sets the version of Docker Compose
version: '3.8'

############## NETWORKS ##############

# Network to connect all the containers in the project
networks:
  inception:
    name: inception

############## VOLUMES ################

# Definition of persistent volumes, ensuring that data is not lost when containers are restarted
volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      o: bind
      type: none
      device: /home/edcastro/data/wordpress
    
  mariadb_data:
    name: mariadb_data
    driver_opts:
      o: bind
      type: none
      device: /home/edcastro/data/mariadb

##############  SERVICES ##############

# Application services, including the MariaDB database, WordPress and the Nginx server
services:
  mariadb:
    image: mariadb:42project
    container_name: mariadb
    env_file:
      - .env
    build: 
      context: requirements/mariadb
      args:
        - ADMIN_NAME=${ADMIN_NAME}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - ROOT_PASSWORD=${ROOT_PASSWORD}
    environment:
      - ADMIN_NAME
      - ADMIN_PASSWORD
      - DATABASE_NAME
      - ROOT_PASSWORD
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306
    restart: on-failure
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:42project
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  nginx:
    depends_on:
      - wordpress
    image: nginx:42project
    container_name: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
